services:
  - type: web
    name: infinite-iq-paywall
    runtime: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      # Set these in the Render Dashboard with real values (or edit here before commit)
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: BASE_URL
        sync: false
      - key: TOKEN_TTL_HOURS
        value: "24"
      - key: MAX_DOWNLOADS_PER_TOKEN
        value: "1"
